### PR TITLE
fixing the reintroduced Unsupported operation: Platform._operatingSystem bug

### LINKED ISSUE #132: Reintroduced issue for Unsupported operation: Platform._operatingSystem
Image

The issue for Unsupported operation: Platform._operatingSystem can be seen again while testing the app in the browser.

 
Image
I guess the issue is caused by the keyboard.dart

### PR DESCRIPTION
**Pull request by Ron1005**
**Platform.isMacOS**  was replaced with 
**defaultTargetPlatform == TargetPlatform.macOS** 
wherever the issue was observed
closes #132

### CODE REVIEW

File: lib/central/help.dart [hunk 1]
```diff
@@ -12,7 +12,7 @@ class HelpMenu extends StatelessWidget {
 
   @override
   Widget build(BuildContext context) {
-    final modifierSymbol = Platform.isMacOS ? '⌘' : '⌃';
```
Comment (ryncmrfrd) [inline lib/central/help.dart:15]: Ah my bad there, thanks for catching this!
